# This is a basic workflow to help you get started with Actions

name: DEVELOP_SEVER_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: make .env file
        run: |
          touch .env
          echo "${{ secrets.env }}" >> .env
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t minmory-backend .
          docker tag minmory-backend secretjuju/minmory-backend:${GITHUB_SHA:7}
          docker push secretjuju/minmory-backend:${GITHUB_SHA:7}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SEVER }}
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          envs: GITHUB_SHA
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            sudo docker pull secretjuju/minmory-backend:${GITHUB_SHA:7}
            sudo docker tag secretjuju/minmory-backend:${GITHUB_SHA:7} minmory-backend
            sudo docker stop server
            sudo docker run -d --rm --name server -p 80:3000
